//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSNServer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSNUploadData1
    {
        public int ID { get; set; }
        public string NodeAddress { get; set; }
        public System.DateTime UploadTime { get; set; }
        public Nullable<decimal> CI { get; set; }
        public Nullable<decimal> AirTemperature { get; set; }
        public Nullable<decimal> SoilHumidity { get; set; }
        public Nullable<decimal> MTA { get; set; }
        public Nullable<decimal> Cover { get; set; }
        public Nullable<decimal> BatA { get; set; }
        public Nullable<decimal> Rssi { get; set; }
        public Nullable<decimal> BatSys { get; set; }
        public int CityID { get; set; }
        public Nullable<decimal> Lai { get; set; }
        public Nullable<decimal> SoilTemperature { get; set; }
        public Nullable<decimal> DIFN { get; set; }
        public Nullable<decimal> AirHumidity { get; set; }
        public Nullable<decimal> MLai { get; set; }
    }
}
